### ISSUE TITLE
Restructure inputs and add upstream registry as a submodule

### ISSUE THREAD

**Issue by hdevalence** [prax-wallet/registry#5]
We should restructure to split apart input data from compilation configs, and add the upstream registry as a submodule so that compiling a registry is deterministic and does not require network access:
```
input-data/
  cosmos-chain-registry # git submodule
configs/
  penumbra-testnet-deimos-6.json
  ...
```
The config structure should have the following data:
- the chain ID
- list of native assets
- overrides for ibc assets (this can be an empty map for now)

**Comment by hdevalence** [comment]
Using a submodule will also allow us to:

- add a CI job that checks that the generated data is clean (since it will be deterministically generated)
- add a CI job that periodically pulls updates from the upstream registry and regenerates our registry

**Comment by grod220** [comment]
I initially started down the submodule route, but got annoyed after waiting a while for the clone from github. It's 159mb. But then I realized that we need only a small fraction of the data the registry hosts. Specific fetching sped up the build significantly given a) we only download the data we need and b) we can then use parallel queries/processing versus waiting on the bulk download to finish.

> compiling a registry is deterministic

Fetching from a specific commit would also render deterministic output that could validate what we check in.

> and does not require network access

A submodule would still need to be fetched from the network in order to make a build. It's only after the repo is cached that repeat generations we be faster. But, I don't really see a use case for that.
